import sqlite3
import uuid
import time
import os
import logging
from typing import Dict, List
from strategy.trfa_engine import TradeForensicEngine
from strategy.sie_engine import SignalImmutabilityEngine
from database.trfa_db import TRFADatabase
from datetime import datetime
from PySide6.QtCore import QObject, Signal

logger = logging.getLogger("TradeManager")

# --- DATA MODELS ---
class TradeStatus:
    WAITING = "Waiting"
    TRIGGERED = "Triggered"
    RUNNING = "Running"
    T1_HIT = "Target 1 Hit"
    T2_HIT = "Target 2 Hit"
    SL_HIT = "Stop Loss Hit"
    EXPIRED = "Expired"
    CANCELLED = "Cancelled"
    CLOSED = "Closed"

class TradeManagerSignals(QObject):
    trade_created = Signal(dict)
    trade_updated = Signal(dict)
    trade_closed = Signal(dict)
    notification = Signal(str, str) # title, message

class TradeManager:
    _instance = None
    
    @classmethod
    def get_instance(cls):
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance
        
    def __init__(self):
        if TradeManager._instance is not None:
            raise Exception("TradeManager is a singleton!")
            
        self.signals = TradeManagerSignals()
        self.active_trades = {} # id -> dict
        self.history = []
        
        # Risk Control
        self.max_trades_per_strategy = 5
        self.trfa = TradeForensicEngine()
        self.trfa_db = TRFADatabase()
        self.sie = SignalImmutabilityEngine()
        
        self._init_db()
        self._load_active_trades()
        
    def _init_db(self):
        os.makedirs("data", exist_ok=True)
        self.db_path = "data/trade_journal.db"
        
        conn = sqlite3.connect(self.db_path)
        c = conn.cursor()
        c.execute('''
            CREATE TABLE IF NOT EXISTS trades (
                id TEXT PRIMARY KEY,
                symbol TEXT,
                signal TEXT,
                timeframe TEXT,
                strategy TEXT,
                entry_price REAL,
                sl REAL,
                t1 REAL,
                t2 REAL,
                rr REAL,
                score REAL,
                confidence REAL,
                quality TEXT,
                created_time TEXT,
                expiry_time TEXT,
                status TEXT,
                exit_price REAL,
                exit_reason TEXT,
                exit_time TEXT,
                pnl REAL,
                pnl_percent REAL
            )
        ''')
        
        # Safely add new columns if they don't exist
        try:
            c.execute("ALTER TABLE trades ADD COLUMN market_regime TEXT DEFAULT 'Unknown'")
        except sqlite3.OperationalError:
            pass
            
        try:
            c.execute("ALTER TABLE trades ADD COLUMN elite_score REAL DEFAULT 0.0")
        except sqlite3.OperationalError:
            pass
            
        conn.commit()
        conn.close()

    def _load_active_trades(self):
        conn = sqlite3.connect(self.db_path)
        c = conn.cursor()
        # Load trades that are not closed/hit targets/sl
        c.execute("SELECT * FROM trades WHERE status IN ('Waiting', 'Triggered', 'Running')")
        rows = c.fetchall()
        cols = [description[0] for description in c.description]
        
        for r in rows:
            trade = dict(zip(cols, r))
            self.active_trades[trade['id']] = trade
            
        conn.close()
        
    def _save_trade(self, t):
        conn = sqlite3.connect(self.db_path)
        c = conn.cursor()
        c.execute('''
            INSERT OR REPLACE INTO trades (
                id, symbol, signal, timeframe, strategy, entry_price, sl, t1, t2, rr, 
                score, confidence, quality, created_time, expiry_time, status, 
                exit_price, exit_reason, exit_time, pnl, pnl_percent, market_regime, elite_score
            )
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
        ''', (
            t.get('id'), t.get('symbol'), t.get('signal'), t.get('timeframe'),
            t.get('strategy'), t.get('entry_price'), t.get('sl'), t.get('t1'),
            t.get('t2'), t.get('rr'), t.get('score'), t.get('confidence'),
            t.get('quality'), t.get('created_time'), t.get('expiry_time'),
            t.get('status'), t.get('exit_price'), t.get('exit_reason'),
            t.get('exit_time'), t.get('pnl'), t.get('pnl_percent'),
            t.get('market_regime', 'Unknown'), t.get('elite_score', 0.0)
        ))
        conn.commit()
        conn.close()

    def receive_signal(self, signal_data):
        """
        Called when a new signal is generated by Intraday/Swing engines.
        """
        strategy = signal_data.get('strategy', 'Unknown')
        
        # Risk Control
        active_count = sum(1 for t in self.active_trades.values() if t['strategy'] == strategy)
        if active_count >= self.max_trades_per_strategy:
            logger.warning(f"Risk Control: Max active trades ({self.max_trades_per_strategy}) reached for {strategy}.")
            return None
            
        trade_id = str(uuid.uuid4())[:8]
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        trade = {
            'id': trade_id,
            'symbol': signal_data.get('symbol'),
            'signal': signal_data.get('signal'),
            'timeframe': signal_data.get('timeframe'),
            'strategy': strategy,
            'entry_price': signal_data.get('entry', 0.0),
            'sl': signal_data.get('sl', 0.0),
            't1': signal_data.get('t1', 0.0),
            't2': signal_data.get('t2', 0.0),
            'rr': signal_data.get('rr', 0.0),
            'score': signal_data.get('score', 0),
            'confidence': signal_data.get('confidence', 0),
            'quality': signal_data.get('quality', 'Unknown'),
            'created_time': now,
            'expiry_time': signal_data.get('expiry_time', ''),
            'status': TradeStatus.WAITING,
            
            # Dynamic fields
            'cmp': 0.0,
            'exit_price': None,
            'exit_reason': None,
            'exit_time': None,
            'pnl': 0.0,
            'pnl_percent': 0.0,
            
            # New fields
            'market_regime': signal_data.get('market_regime', 'Unknown'),
            'elite_score': signal_data.get('elite_score', 0.0)
        }
        
        trade = self.sie.lock_signal(trade)
        
        self.active_trades[trade_id] = trade
        self._save_trade(trade)
        
        self.signals.trade_created.emit(trade)
        self.signals.notification.emit("New Trade", f"{trade['signal']} {trade['symbol']} at {trade['entry_price']}")
        return trade_id
        
    def modify_trade_parameters(self, trade_id: str, updated_fields: dict) -> bool:
        """
        Attempt to modify a trade. Will be blocked by SIE if it violates immutability rules.
        """
        if trade_id not in self.active_trades:
            return False
            
        original = self.active_trades[trade_id].copy()
        updated = original.copy()
        updated.update(updated_fields)
        
        is_valid, msg = self.sie.validate_update(original, updated)
        if not is_valid:
            logger.warning(f"TradeManager rejected update for {trade_id}: {msg}")
            return False
            
        self.active_trades[trade_id] = updated
        self._save_trade(updated)
        self.signals.trade_updated.emit(updated)
        return True

    def update_market_price(self, symbol, cmp):
        """
        Called by DataManager or background loop when price updates.
        """
        for t_id, t in list(self.active_trades.items()):
            if t['symbol'] == symbol:
                t['cmp'] = cmp
                
                entry = t['entry_price']
                is_buy = t['signal'] == 'BUY'
                
                # Update PnL
                if t['status'] in [TradeStatus.TRIGGERED, TradeStatus.RUNNING]:
                    if is_buy:
                        t['pnl'] = cmp - entry
                    else:
                        t['pnl'] = entry - cmp
                        
                    t['pnl_percent'] = (t['pnl'] / entry) * 100 if entry > 0 else 0
                
                # Check Triggers
                if t['status'] == TradeStatus.WAITING:
                    if (is_buy and cmp >= entry) or (not is_buy and cmp <= entry):
                        t['status'] = TradeStatus.TRIGGERED
                        self.signals.notification.emit("Trade Triggered", f"{t['symbol']} entered at {cmp}")
                
                elif t['status'] in [TradeStatus.TRIGGERED, TradeStatus.RUNNING]:
                    reason = None
                    if is_buy:
                        if cmp >= t['t2'] and t['t2'] > 0: reason = TradeStatus.T2_HIT
                        elif cmp >= t['t1'] and t['t1'] > 0 and t['status'] != TradeStatus.T1_HIT:
                            t['status'] = TradeStatus.T1_HIT
                            self.signals.notification.emit("Target 1 Hit", f"{t['symbol']} hit T1 at {cmp}")
                        elif cmp <= t['sl'] and t['sl'] > 0: reason = TradeStatus.SL_HIT
                    else:
                        if cmp <= t['t2'] and t['t2'] > 0: reason = TradeStatus.T2_HIT
                        elif cmp <= t['t1'] and t['t1'] > 0 and t['status'] != TradeStatus.T1_HIT:
                            t['status'] = TradeStatus.T1_HIT
                            self.signals.notification.emit("Target 1 Hit", f"{t['symbol']} hit T1 at {cmp}")
                        elif cmp >= t['sl'] and t['sl'] > 0: reason = TradeStatus.SL_HIT
                        
                    if reason:
                        self.close_trade(t_id, cmp, reason)
                
                self.signals.trade_updated.emit(t)

    def close_trade(self, trade_id, exit_price, reason):
        if trade_id in self.active_trades:
            t = self.active_trades[trade_id]
            t['status'] = TradeStatus.CLOSED if "Hit" not in reason else reason
            t['exit_price'] = exit_price
            t['exit_reason'] = reason
            t['exit_time'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            
            # Final PnL
            entry = t['entry_price']
            is_buy = t['signal'] == 'BUY'
            if is_buy: t['pnl'] = exit_price - entry
            else: t['pnl'] = entry - exit_price
            t['pnl_percent'] = (t['pnl'] / entry) * 100 if entry > 0 else 0
            
            self._save_trade(t)
            del self.active_trades[trade_id]
            
            # --- TRFA FORENSIC ANALYSIS ---
            try:
                report = self.trfa.analyze_closed_trade(t)
                self.trfa_db.save_report(report, t)
            except Exception as e:
                logger.exception("Failed to run TRFA")
                
            self.signals.trade_closed.emit(t)
            self.signals.notification.emit("Trade Closed", f"{t['symbol']} closed: {reason} at {exit_price}")

    def get_statistics(self):
        conn = sqlite3.connect(self.db_path)
        c = conn.cursor()
        c.execute("SELECT * FROM trades")
        all_trades = [dict(zip([d[0] for d in c.description], r)) for r in c.fetchall()]
        conn.close()
        
        total_closed = [t for t in all_trades if t['status'] not in ['Waiting', 'Triggered', 'Running']]
        wins = [t for t in total_closed if t['pnl'] > 0]
        losses = [t for t in total_closed if t['pnl'] <= 0]
        
        today = datetime.now().strftime("%Y-%m-%d")
        todays_trades = [t for t in all_trades if t['created_time'].startswith(today)]
        
        win_rate = (len(wins) / len(total_closed) * 100) if total_closed else 0.0
        total_pnl = sum(t['pnl'] for t in total_closed)
        
        return {
            "today_trades": len(todays_trades),
            "open_trades": len(self.active_trades),
            "closed_trades": len(total_closed),
            "win_rate": round(win_rate, 2),
            "total_pnl": round(total_pnl, 2)
        }
