import os
import json
import logging
from datetime import datetime
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

class TradeLifecycleEngine:
    """
    MASTER-17: TRADE LIFECYCLE ENGINE VERSION 1.0
    Tracks, validates, updates, and records the entire journey of a trade.
    """
    
    STATES = [
        "SIGNAL_CREATED",
        "WAITING_ENTRY",
        "ENTRY_TRIGGERED",
        "ACTIVE",
        "TARGET_1_HIT",
        "TARGET_2_HIT",
        "TARGET_3_HIT",
        "TRAILING_STOP_ACTIVE",
        "EXIT_SIGNAL",
        "POSITION_CLOSED",
        "TRADE_REPLAY",
        "TRADE_JOURNAL",
        "ARCHIVED"
    ]
    
    def __init__(self, data_dir="data"):
        self.data_dir = data_dir
        if not os.path.exists(self.data_dir):
            os.makedirs(self.data_dir)
            
        self.archive_file = os.path.join(self.data_dir, "trade_lifecycle_archive.json")
        self._trades = self._load_archive()
        
    def _load_archive(self) -> Dict[str, Any]:
        if os.path.exists(self.archive_file):
            try:
                with open(self.archive_file, "r") as f:
                    return json.load(f)
            except Exception as e:
                logger.error(f"Error loading trade archive: {e}")
                return {}
        return {}
        
    def _save_archive(self):
        try:
            with open(self.archive_file, "w") as f:
                json.dump(self._trades, f, indent=4)
        except Exception as e:
            logger.error(f"Error saving trade archive: {e}")
            
    def _generate_trade_id(self) -> str:
        date_str = datetime.now().strftime("%Y%m%d")
        
        # Count existing trades today
        count = 1
        for tid in self._trades.keys():
            if tid.startswith(f"AT-{date_str}-"):
                count += 1
                
        return f"AT-{date_str}-{count:03d}"
        
    def create_signal(self, trade_data: Dict[str, Any]) -> str:
        """
        Registers a new trade into the lifecycle upon SIGNAL_CREATED.
        """
        trade_id = self._generate_trade_id()
        now = datetime.now()
        
        trade = {
            "Trade_ID": trade_id,
            "Date": now.strftime("%Y-%m-%d"),
            "Time": now.strftime("%H:%M:%S"),
            "Scanner": trade_data.get("Scanner", "Active Trading AI"),
            "Symbol": trade_data.get("Symbol", "UNKNOWN"),
            "Direction": "BUY" if "BUY" in str(trade_data.get("Signal", "")) else "SELL",
            "Entry": float(trade_data.get("Entry", 0)),
            "Stop_Loss": float(trade_data.get("Stop Loss", 0)),
            "Target_1": float(trade_data.get("Target 1", 0)),
            "Target_2": float(trade_data.get("Target 2", 0)),
            "Confidence": float(trade_data.get("Confidence", 0)),
            "Elite_Score": float(trade_data.get("Score", 0)),
            "Reason": trade_data.get("Reason Selected", ""),
            "State": "SIGNAL_CREATED",
            "History": [
                {
                    "state": "SIGNAL_CREATED",
                    "timestamp": now.isoformat(),
                    "note": "Signal generated by system."
                }
            ],
            "Execution": {}
        }
        
        self._trades[trade_id] = trade
        self._save_archive()
        return trade_id
        
    def update_state(self, trade_id: str, new_state: str, note: str = "", updates: Dict[str, Any] = None):
        """
        Transitions the trade to a new state and records the history.
        """
        if trade_id not in self._trades:
            logger.error(f"Trade ID {trade_id} not found.")
            return False
            
        if new_state not in self.STATES:
            logger.error(f"Invalid state: {new_state}")
            return False
            
        trade = self._trades[trade_id]
        trade["State"] = new_state
        
        history_entry = {
            "state": new_state,
            "timestamp": datetime.now().isoformat(),
            "note": note
        }
        trade["History"].append(history_entry)
        
        if updates:
            for k, v in updates.items():
                trade["Execution"][k] = v
                
        # If moving to POSITION_CLOSED, generate journal automatically
        if new_state == "POSITION_CLOSED":
            self._generate_journal(trade_id)
            
        self._save_archive()
        return True
        
    def trigger_entry(self, trade_id: str, entry_price: float, slippage: float = 0.0):
        self.update_state(
            trade_id, 
            "ENTRY_TRIGGERED", 
            f"Entered at {entry_price}",
            {
                "Executed_Entry": entry_price,
                "Slippage": slippage,
                "Entry_Time": datetime.now().isoformat()
            }
        )
        self.update_state(trade_id, "ACTIVE", "Trade is now fully active.")
        
    def hit_target(self, trade_id: str, target_num: int, price: float):
        state = f"TARGET_{target_num}_HIT"
        if state not in self.STATES:
            state = "TARGET_1_HIT"
            
        trade = self._trades.get(trade_id, {})
        entry = float(trade.get("Execution", {}).get("Executed_Entry", trade.get("Entry", 0)))
        
        if entry > 0:
            if trade.get("Direction") == "BUY":
                profit_pct = ((price - entry) / entry) * 100
            else:
                profit_pct = ((entry - price) / entry) * 100
        else:
            profit_pct = 0.0
            
        updates = {
            f"Target_{target_num}_Hit_Time": datetime.now().isoformat(),
            f"Target_{target_num}_Hit_Price": price,
            f"Profit_At_Target_{target_num}": profit_pct
        }
        
        self.update_state(trade_id, state, f"Hit Target {target_num} at {price}", updates)
        
    def enable_trailing_stop(self, trade_id: str, current_sl: float):
        updates = {"Trailing_Stop": current_sl}
        self.update_state(trade_id, "TRAILING_STOP_ACTIVE", f"Trailing Stop active at {current_sl}", updates)
        
    def update_trailing_stop(self, trade_id: str, new_sl: float):
        trade = self._trades.get(trade_id)
        if trade:
            trade["Execution"]["Trailing_Stop"] = new_sl
            trade["History"].append({
                "state": "TS_UPDATED",
                "timestamp": datetime.now().isoformat(),
                "note": f"TS moved to {new_sl}"
            })
            self._save_archive()
            
    def close_position(self, trade_id: str, exit_price: float, exit_reason: str):
        trade = self._trades.get(trade_id, {})
        entry = float(trade.get("Execution", {}).get("Executed_Entry", trade.get("Entry", 0)))
        
        # P&L Calculation
        if entry > 0:
            if trade.get("Direction") == "BUY":
                net_profit_pct = ((exit_price - entry) / entry) * 100
            else:
                net_profit_pct = ((entry - exit_price) / entry) * 100
        else:
            net_profit_pct = 0.0
            
        updates = {
            "Exit_Time": datetime.now().isoformat(),
            "Exit_Price": exit_price,
            "Exit_Reason": exit_reason,
            "Net_Profit_Pct": net_profit_pct
        }
        
        self.update_state(trade_id, "EXIT_SIGNAL", f"Exit triggered: {exit_reason}")
        self.update_state(trade_id, "POSITION_CLOSED", f"Position closed at {exit_price}", updates)
        
    def _generate_journal(self, trade_id: str):
        trade = self._trades.get(trade_id)
        if not trade: return
        
        net_profit = trade.get("Execution", {}).get("Net_Profit_Pct", 0)
        
        # AI Replay & Journal simulation
        replay = {
            "Analysis": "Trade executed as per plan." if net_profit > 0 else "Trade failed to hold momentum.",
            "Why_Worked": "Strong volume and trend alignment." if net_profit > 0 else "N/A",
            "Why_Failed": "N/A" if net_profit > 0 else "Market rotation or sudden fake breakout."
        }
        
        journal = {
            "Trade_Summary": f"Closed with {net_profit:.2f}% return.",
            "Lessons": "Follow trailing stop rules strictly.",
            "Mistakes": "None" if net_profit > 0 else "Potential late entry or missed warning signs.",
            "Strengths": "Good risk reward." if trade.get("Confidence", 0) > 85 else "Average",
            "Weaknesses": "N/A",
            "AI_Observations": "Capital protection logic performed correctly."
        }
        
        trade["Replay"] = replay
        trade["Journal"] = journal
        
        self.update_state(trade_id, "TRADE_REPLAY", "Replay generated.")
        self.update_state(trade_id, "TRADE_JOURNAL", "Journal generated.")
        self.update_state(trade_id, "ARCHIVED", "Trade lifecycle complete. Archived permanently.")
        
    def get_dashboard_data(self) -> List[Dict[str, Any]]:
        """
        Returns a list of trades formatted for a Dashboard.
        """
        dash = []
        for tid, t in self._trades.items():
            dash.append({
                "Trade ID": tid,
                "Symbol": t.get("Symbol"),
                "Direction": t.get("Direction"),
                "Status": t.get("State"),
                "Entry": t.get("Execution", {}).get("Executed_Entry", t.get("Entry")),
                "SL": t.get("Execution", {}).get("Trailing_Stop", t.get("Stop_Loss")),
                "Target": t.get("Target_1"),
                "P&L %": round(t.get("Execution", {}).get("Net_Profit_Pct", 0), 2),
                "Confidence": t.get("Confidence"),
                "Elite Score": t.get("Elite_Score")
            })
        return dash
