"""
Scoring rules and configuration module for RAHUUL_RADAR.
Defines the weight distribution and signal generation thresholds for the ranking engine.
"""
from dataclasses import dataclass
from enum import Enum

@dataclass(frozen=True)
class ScoringWeights:
    """
    Data structure defining the precise weight allocation for technical parameters.
    The sum of all individual weights must equal the total (100).
    """
    trend: int = 25
    momentum: int = 20
    structure: int = 20
    volume: int = 10
    volatility: int = 10
    relative_strength: int = 10
    risk_reward: int = 5
    total: int = 100


class SignalStrength(str, Enum):
    """
    Categorical enumeration of valid trading signals generated by the score engine.
    """
    STRONG_BUY = "STRONG_BUY"
    BUY = "BUY"
    WATCH = "WATCH"
    WEAK = "WEAK"
    AVOID = "AVOID"
    SELL = "SELL"
    STRONG_SELL = "STRONG_SELL"


def score_to_signal(score: float) -> SignalStrength:
    """
    Converts a numerical total score into a categorical trading signal.
    
    Rules:
        90+      -> STRONG_BUY
        80-89.99 -> BUY
        70-79.99 -> WATCH
        60-69.99 -> WEAK
        Below 60 -> AVOID
        
    Args:
        score: The aggregated technical score (typically 0-100).
        
    Returns:
        SignalStrength: The calculated categorical signal.
    """
    if score >= 90.0:
        return SignalStrength.STRONG_BUY
    elif score >= 80.0:
        return SignalStrength.BUY
    elif score >= 70.0:
        return SignalStrength.WATCH
    elif score >= 60.0:
        return SignalStrength.WEAK
    else:
        return SignalStrength.AVOID
