"""
Market Universe Module (Sprint 151)
Provides dynamic lists of NSE stocks grouped by F&O, NIFTY 200, NIFTY 500, Sector, and Market Cap.
"""
from typing import List, Dict

# Complete Live NSE F&O Universe (184 constituents)
FNO_UNIVERSE = [
    {"symbol": "AARTIIND.NS", "sector": "Chemicals", "mcap": "Mid Cap"},
    {"symbol": "ABB.NS", "sector": "Capital Goods", "mcap": "Large Cap"},
    {"symbol": "ABBOTINDIA.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "ABCAPITAL.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "ABFRL.NS", "sector": "Retail", "mcap": "Mid Cap"},
    {"symbol": "ACC.NS", "sector": "Cement", "mcap": "Large Cap"},
    {"symbol": "ADANIENT.NS", "sector": "Diversified", "mcap": "Large Cap"},
    {"symbol": "ADANIPORTS.NS", "sector": "Infrastructure", "mcap": "Large Cap"},
    {"symbol": "ALKEM.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "AMBUJACEM.NS", "sector": "Cement", "mcap": "Large Cap"},
    {"symbol": "APOLLOHOSP.NS", "sector": "Healthcare", "mcap": "Large Cap"},
    {"symbol": "APOLLOTYRE.NS", "sector": "Auto Ancillary", "mcap": "Mid Cap"},
    {"symbol": "ASHOKLEY.NS", "sector": "Auto", "mcap": "Large Cap"},
    {"symbol": "ASIANPAINT.NS", "sector": "Consumer Durables", "mcap": "Large Cap"},
    {"symbol": "ASTRAL.NS", "sector": "Building Materials", "mcap": "Mid Cap"},
    {"symbol": "ATUL.NS", "sector": "Chemicals", "mcap": "Mid Cap"},
    {"symbol": "AUBANK.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "AUROPHARMA.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "AXISBANK.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "BAJAJ-AUTO.NS", "sector": "Auto", "mcap": "Large Cap"},
    {"symbol": "BAJAJFINSV.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "BAJFINANCE.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "BALKRISIND.NS", "sector": "Auto Ancillary", "mcap": "Mid Cap"},
    {"symbol": "BANDHANBNK.NS", "sector": "Banking", "mcap": "Mid Cap"},
    {"symbol": "BANKBARODA.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "BATAINDIA.NS", "sector": "Consumer Durables", "mcap": "Mid Cap"},
    {"symbol": "BEL.NS", "sector": "Capital Goods", "mcap": "Large Cap"},
    {"symbol": "BERGEPAINT.NS", "sector": "Consumer Durables", "mcap": "Large Cap"},
    {"symbol": "BHARATFORG.NS", "sector": "Auto Ancillary", "mcap": "Large Cap"},
    {"symbol": "BHARTIARTL.NS", "sector": "Telecom", "mcap": "Large Cap"},
    {"symbol": "BHEL.NS", "sector": "Capital Goods", "mcap": "Large Cap"},
    {"symbol": "BIOCON.NS", "sector": "Pharma", "mcap": "Mid Cap"},
    {"symbol": "BOSCHLTD.NS", "sector": "Auto Ancillary", "mcap": "Large Cap"},
    {"symbol": "BPCL.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "BRITANNIA.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "BSOFT.NS", "sector": "IT", "mcap": "Mid Cap"},
    {"symbol": "CANBK.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "CANFINHOME.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "CHAMBLFERT.NS", "sector": "Fertilizers", "mcap": "Mid Cap"},
    {"symbol": "CHOLAFIN.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "CIPLA.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "COALINDIA.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "COFORGE.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "COLPAL.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "CONCOR.NS", "sector": "Logistics", "mcap": "Large Cap"},
    {"symbol": "COROMANDEL.NS", "sector": "Fertilizers", "mcap": "Mid Cap"},
    {"symbol": "CROMPTON.NS", "sector": "Consumer Durables", "mcap": "Mid Cap"},
    {"symbol": "CUB.NS", "sector": "Banking", "mcap": "Mid Cap"},
    {"symbol": "CUMMINSIND.NS", "sector": "Capital Goods", "mcap": "Large Cap"},
    {"symbol": "DABUR.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "DALBHARAT.NS", "sector": "Cement", "mcap": "Mid Cap"},
    {"symbol": "DEEPAKNTR.NS", "sector": "Chemicals", "mcap": "Mid Cap"},
    {"symbol": "DELHIVERY.NS", "sector": "Logistics", "mcap": "Mid Cap"},
    {"symbol": "DIVISLAB.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "DIXON.NS", "sector": "Consumer Durables", "mcap": "Large Cap"},
    {"symbol": "DLF.NS", "sector": "Realty", "mcap": "Large Cap"},
    {"symbol": "DRREDDY.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "EICHERMOT.NS", "sector": "Auto", "mcap": "Large Cap"},
    {"symbol": "ESCORTS.NS", "sector": "Auto", "mcap": "Mid Cap"},
    {"symbol": "EXIDEIND.NS", "sector": "Auto Ancillary", "mcap": "Mid Cap"},
    {"symbol": "FEDERALBNK.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "GAIL.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "GLENMARK.NS", "sector": "Pharma", "mcap": "Mid Cap"},
    {"symbol": "GMRAIRPORT.NS", "sector": "Infrastructure", "mcap": "Mid Cap"},
    {"symbol": "GNFC.NS", "sector": "Fertilizers", "mcap": "Mid Cap"},
    {"symbol": "GODREJCP.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "GODREJPROP.NS", "sector": "Realty", "mcap": "Large Cap"},
    {"symbol": "GRASIM.NS", "sector": "Diversified", "mcap": "Large Cap"},
    {"symbol": "GUJGASLTD.NS", "sector": "Energy", "mcap": "Mid Cap"},
    {"symbol": "HAL.NS", "sector": "Capital Goods", "mcap": "Large Cap"},
    {"symbol": "HAVELLS.NS", "sector": "Consumer Durables", "mcap": "Large Cap"},
    {"symbol": "HCLTECH.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "HDFCAMC.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "HDFCBANK.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "HDFCLIFE.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "HEROMOTOCO.NS", "sector": "Auto", "mcap": "Large Cap"},
    {"symbol": "HINDALCO.NS", "sector": "Metal", "mcap": "Large Cap"},
    {"symbol": "HINDCOPPER.NS", "sector": "Metal", "mcap": "Mid Cap"},
    {"symbol": "HINDPETRO.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "HINDUNILVR.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "ICICIBANK.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "ICICIGI.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "ICICIPRULI.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "IDEA.NS", "sector": "Telecom", "mcap": "Mid Cap"},
    {"symbol": "IDFCFIRSTB.NS", "sector": "Banking", "mcap": "Mid Cap"},
    {"symbol": "IEX.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "IGL.NS", "sector": "Energy", "mcap": "Mid Cap"},
    {"symbol": "INDHOTEL.NS", "sector": "Hospitality", "mcap": "Large Cap"},
    {"symbol": "INDIAMART.NS", "sector": "Internet", "mcap": "Mid Cap"},
    {"symbol": "INDIANB.NS", "sector": "Banking", "mcap": "Mid Cap"},
    {"symbol": "INDIGO.NS", "sector": "Aviation", "mcap": "Large Cap"},
    {"symbol": "INDUSINDBK.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "INDUSTOWER.NS", "sector": "Telecom", "mcap": "Large Cap"},
    {"symbol": "INFY.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "IOC.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "IPCALAB.NS", "sector": "Pharma", "mcap": "Mid Cap"},
    {"symbol": "IRCTC.NS", "sector": "Tourism", "mcap": "Large Cap"},
    {"symbol": "IREDA.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "IRFC.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "ITC.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "JINDALSTEL.NS", "sector": "Metal", "mcap": "Large Cap"},
    {"symbol": "JIOFIN.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "JKCEMENT.NS", "sector": "Cement", "mcap": "Mid Cap"},
    {"symbol": "JSWSTEEL.NS", "sector": "Metal", "mcap": "Large Cap"},
    {"symbol": "JUBLFOOD.NS", "sector": "Retail", "mcap": "Mid Cap"},
    {"symbol": "KALYANKJIL.NS", "sector": "Retail", "mcap": "Mid Cap"},
    {"symbol": "KEI.NS", "sector": "Capital Goods", "mcap": "Mid Cap"},
    {"symbol": "KOTAKBANK.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "KPITTECH.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "LALPATHLAB.NS", "sector": "Healthcare", "mcap": "Mid Cap"},
    {"symbol": "LAURUSLABS.NS", "sector": "Pharma", "mcap": "Mid Cap"},
    {"symbol": "LT.NS", "sector": "Infrastructure", "mcap": "Large Cap"},
    {"symbol": "LTF.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "LTIM.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "LTTS.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "LUPIN.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "M&M.NS", "sector": "Auto", "mcap": "Large Cap"},
    {"symbol": "M&MFIN.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "MANAPPURAM.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "MARICO.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "MARUTI.NS", "sector": "Auto", "mcap": "Large Cap"},
    {"symbol": "MCX.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "METROPOLIS.NS", "sector": "Healthcare", "mcap": "Mid Cap"},
    {"symbol": "MFSL.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "MGL.NS", "sector": "Energy", "mcap": "Mid Cap"},
    {"symbol": "MOTHERSON.NS", "sector": "Auto Ancillary", "mcap": "Large Cap"},
    {"symbol": "MPHASIS.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "MRF.NS", "sector": "Auto Ancillary", "mcap": "Large Cap"},
    {"symbol": "MUTHOOTFIN.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "NATIONALUM.NS", "sector": "Metal", "mcap": "Mid Cap"},
    {"symbol": "NAVINFLUOR.NS", "sector": "Chemicals", "mcap": "Mid Cap"},
    {"symbol": "NCC.NS", "sector": "Infrastructure", "mcap": "Mid Cap"},
    {"symbol": "NESTLEIND.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "NHPC.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "NMDC.NS", "sector": "Metal", "mcap": "Large Cap"},
    {"symbol": "NTPC.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "NUVAMA.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "OBEROIRLTY.NS", "sector": "Realty", "mcap": "Large Cap"},
    {"symbol": "OFSS.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "OIL.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "ONGC.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "PAGEIND.NS", "sector": "Textiles", "mcap": "Large Cap"},
    {"symbol": "PAYTM.NS", "sector": "Fintech", "mcap": "Mid Cap"},
    {"symbol": "PEL.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "PERSISTENT.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "PETRONET.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "PFC.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "PHOENIXLTD.NS", "sector": "Realty", "mcap": "Large Cap"},
    {"symbol": "PIDILITIND.NS", "sector": "Chemicals", "mcap": "Large Cap"},
    {"symbol": "PIIND.NS", "sector": "Chemicals", "mcap": "Large Cap"},
    {"symbol": "PNB.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "POLICYBZR.NS", "sector": "Fintech", "mcap": "Mid Cap"},
    {"symbol": "POLYCAB.NS", "sector": "Capital Goods", "mcap": "Large Cap"},
    {"symbol": "POWERGRID.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "PRESTIGE.NS", "sector": "Realty", "mcap": "Mid Cap"},
    {"symbol": "PVRINOX.NS", "sector": "Media", "mcap": "Mid Cap"},
    {"symbol": "RAMCOCEM.NS", "sector": "Cement", "mcap": "Mid Cap"},
    {"symbol": "RBLBANK.NS", "sector": "Banking", "mcap": "Mid Cap"},
    {"symbol": "RECLTD.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "RELIANCE.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "SAIL.NS", "sector": "Metal", "mcap": "Large Cap"},
    {"symbol": "SBICARD.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "SBILIFE.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "SBIN.NS", "sector": "Banking", "mcap": "Large Cap"},
    {"symbol": "SHREECEM.NS", "sector": "Cement", "mcap": "Large Cap"},
    {"symbol": "SHRIRAMFIN.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "SIEMENS.NS", "sector": "Capital Goods", "mcap": "Large Cap"},
    {"symbol": "SJVN.NS", "sector": "Energy", "mcap": "Mid Cap"},
    {"symbol": "SRF.NS", "sector": "Chemicals", "mcap": "Large Cap"},
    {"symbol": "SUNPHARMA.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "SUNTV.NS", "sector": "Media", "mcap": "Mid Cap"},
    {"symbol": "SUPREMEIND.NS", "sector": "Building Materials", "mcap": "Mid Cap"},
    {"symbol": "SUZLON.NS", "sector": "Capital Goods", "mcap": "Mid Cap"},
    {"symbol": "SYNGENE.NS", "sector": "Pharma", "mcap": "Mid Cap"},
    {"symbol": "TATACHEMICALS.NS", "sector": "Chemicals", "mcap": "Mid Cap"},
    {"symbol": "TATACOMM.NS", "sector": "Telecom", "mcap": "Mid Cap"},
    {"symbol": "TATACONSUM.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "TATAELEXSI.NS", "sector": "IT", "mcap": "Mid Cap"},
    {"symbol": "TATAMOTORS.NS", "sector": "Auto", "mcap": "Large Cap"},
    {"symbol": "TATAPOWER.NS", "sector": "Energy", "mcap": "Large Cap"},
    {"symbol": "TATASTEEL.NS", "sector": "Metal", "mcap": "Large Cap"},
    {"symbol": "TCS.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "TECHM.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "TITAN.NS", "sector": "Consumer Durables", "mcap": "Large Cap"},
    {"symbol": "TORNTPHARM.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "TRENT.NS", "sector": "Retail", "mcap": "Large Cap"},
    {"symbol": "TVSMOTOR.NS", "sector": "Auto", "mcap": "Large Cap"},
    {"symbol": "UBL.NS", "sector": "FMCG", "mcap": "Large Cap"},
    {"symbol": "ULTRACEMCO.NS", "sector": "Cement", "mcap": "Large Cap"},
    {"symbol": "UPL.NS", "sector": "Chemicals", "mcap": "Large Cap"},
    {"symbol": "VEDL.NS", "sector": "Metal", "mcap": "Large Cap"},
    {"symbol": "VOLTAS.NS", "sector": "Consumer Durables", "mcap": "Large Cap"},
    {"symbol": "WIPRO.NS", "sector": "IT", "mcap": "Large Cap"},
    {"symbol": "YESBANK.NS", "sector": "Banking", "mcap": "Mid Cap"},
    {"symbol": "ZEEL.NS", "sector": "Media", "mcap": "Mid Cap"},
    {"symbol": "ZOMATO.NS", "sector": "Internet", "mcap": "Large Cap"},
    {"symbol": "ZYDUSLIFE.NS", "sector": "Pharma", "mcap": "Large Cap"}
]

# Dedicated NIFTY 200 Universe (200 constituents)
NIFTY200_UNIVERSE = list(FNO_UNIVERSE) + [
    {"symbol": "NYKAA.NS", "sector": "Retail", "mcap": "Mid Cap"},
    {"symbol": "AWL.NS", "sector": "FMCG", "mcap": "Mid Cap"},
    {"symbol": "HUDCO.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "MANKIND.NS", "sector": "Pharma", "mcap": "Large Cap"},
    {"symbol": "SOLARINDS.NS", "sector": "Chemicals", "mcap": "Large Cap"},
    {"symbol": "CDSL.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "BSE.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "ANGELONE.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "RVNL.NS", "sector": "Infrastructure", "mcap": "Mid Cap"},
    {"symbol": "LICI.NS", "sector": "Financial", "mcap": "Large Cap"},
    {"symbol": "POONAWALLA.NS", "sector": "Financial", "mcap": "Mid Cap"},
    {"symbol": "MAPMYINDIA.NS", "sector": "Tech", "mcap": "Mid Cap"},
    {"symbol": "MAHSEAMLES.NS", "sector": "Industrial", "mcap": "Mid Cap"},
    {"symbol": "KAYNES.NS", "sector": "Electronics", "mcap": "Mid Cap"},
    {"symbol": "FACT.NS", "sector": "Chemicals", "mcap": "Mid Cap"},
    {"symbol": "SUVENPHAR.NS", "sector": "Pharma", "mcap": "Mid Cap"}
]

def get_fno_symbols() -> List[Dict]:
    """Returns the complete Live NSE F&O Equity Universe (184 stocks)."""
    return FNO_UNIVERSE

def get_nifty200_symbols() -> List[Dict]:
    """Returns dedicated NIFTY 200 constituents (200 stocks)."""
    return NIFTY200_UNIVERSE

def get_all_symbols() -> List[Dict]:
    """Returns default NIFTY 200 universe for general queries."""
    return NIFTY200_UNIVERSE
